### ISSUE TITLE
Test AKS deployment from start to finish

### ISSUE THREAD

**Issue by dtollaku** [k8-proxy/p1-stakeholder-requests#15]
We need to replicate AKS deployment from start to finish, to make sure it can be replicated. There is a clean repo with all necessary scripts, terraform code and helm charts, On the read me are all necessary information to stand it up.  https://github.com/filetrust/icap-terraform-aks-deployment

**Comment by azopat** [comment]
I had couple of issues here and there but i was finally able to complete the deployment  :  

azopats-MBP:icap-terraform-aks-deployment azopat$ kubectl get nodes
NAME                                   STATUS   ROLES   AGE   VERSION
aks-icaptestnode-14624445-vmss000000   Ready    agent   27h   v1.17.13

azopats-MBP:icap-terraform-aks-deployment azopat$ kubectl -n icap-adaptation get pods
NAME                                        READY   STATUS      RESTARTS   AGE
adaptation-service-769c7bf6fb-dct7j         1/1     Running     5          39m
event-submission-service-6b7c87d8dd-cqtnk   1/1     Running     5          39m
mvp-icap-service-5468b656d9-57x7v           1/1     Running     0          39m
pod-janitor-1605566280-85r58                0/1     Completed   0          8s
policy-update-service-8684f8558f-57s89      1/1     Running     0          39m
rabbitmq-controller-q5rnn                   1/1     Running     0          39m

**Comment by azopat** [comment]
Issues encountered  : 
- create-az-storage-account.sh doesn't exist, instead it should be create-az-storage-account-test.sh
- Vault name gw-tfstate-vault-test  already exist so i had to rename it to something else
- Storage account name tfstate already exist so i had to rename
- create-ns-secrets.sh script name is not correct, good name is create-ns-docker-secret.sh
- I didn't had permissions to create principal so someone did it for me and i just set the environment variables
- terraform init was failing because it except also modules aks02 and resource-group-02, needed just to rename existing ones
- export export $SP_USERNAME=spusername should be instead export SP_USERNAME=spusername (same goes to all similar exports)
